sudo:required
services:
  - docker

before_install:
  - docker build -t adelelfar256/docker-react -f Dockerfile.dev .
# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference

script:
  - docker run -e CI=true adelelfar256/docker-react npm run test