version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules #execulte node modules 
      - .:/app #app folder from outside to inside contrainer


  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules #execulte node modules 
      - .:/app #app folder from outside to inside contrainer
    command: ["npm","run","test"]