version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  eb-demo:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Does docker even exist
          command: docker -v
      - run: docker build -t adelelfar256/docker-react -f Dockerfile.dev .
      - run:
          name: Deploying
          command: eb deploy Docker-env
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - eb-demo:
          context: aws
          filters:
            branches:
              only:
                - master