version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Does docker even exist
                command: docker -v
            - run: docker build -t adelelfar256/docker-react -f Dockerfile.dev .
            - run:
                name: Deploying
                command: eb deploy Docker-env

workflows:
  build-and-test:
    jobs:
      - build-and-test:
          context: aws
          filters:
            branches:
              only:
                - master
