version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
jobs:
  eb-demo:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Does docker even exist
          command: docker -v
      - run: docker build -t adelelfar256/docker-react -f Dockerfile.dev .

      - run:
          name: Installing deployment dependencies
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python3-pip python-dev-is-python2 build-essential
            sudo pip install  setuptools
            sudo pip install awsebcli 
      #- run: yes n | eb init
      - run:
          name: Deploying
          command: eb deploy Docker-env
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - eb-demo:
          context: aws
          filters:
            branches:
              only:
                - master