
version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "build"
          command: docker build -t adelelfar256/docker-react -f Dockerfile.dev .

      - run:
          name: "test"
          command: docker run -e CI=true adelelfar256/docker-react npm run test
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
